# Generated by Django 2.2.5 on 2019-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alarm',
            field=models.TimeField(null=True),
        ),
    ]
