# Generated by Django 2.2.5 on 2019-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondey', '0003_auto_20191006_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
