# Generated by Django 2.2.5 on 2019-10-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mondey', '0007_auto_20191027_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryhistory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categoryhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='customcategory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='incomehistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='user_id',
            new_name='user',
        ),
    ]
