# Generated by Django 2.2.5 on 2019-10-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mondey', '0008_auto_20191027_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='password',
        ),
    ]
